version: "3.8"

services:
  mymongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "mongoadmin"

  backend:
    build: ./
    ports:
      - "5050:5050"
    depends_on:
      - mymongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data: